name: do_cu_di
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_app_name: ^0.1.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15
  http: ^0.13.4
  logger: ^1.1.0  # logger
  flash: ^2.0.1 # snackbar
  webview_flutter: ^2.1.2 # load url in app
  flutter_svg: ^1.0.3 # svg render
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.1.1 # slider
  shimmer: ^2.0.0 #item loading
  flutter_screenutil: ^5.0.0+2  #flutter_screenutil
  intl: ^0.17.0
  cached_network_image: ^3.1.0  # cache image

flutter_app_name:
  name: "Đồ cũ đi"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  get_it: ^7.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic